server:
  port: 8082


spring:
  application:
    name: poll-runner

zuul:
  host: gateway

logging:
  level:
    root: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
