version: '3.7'
services:
  discovery-service:
    image: "com.scriptterror/discovery-service:0.1"
    ports:
      - 8761:8761
    env_file:
      - "./discovery-service/config.env"
  
  gateway:
    image: 'com.scriptterror/gateway:0.1'
    env_file:
      - "./gateway/config.env"
    ports:
      - 8080:8080
    depends_on:
      - discovery-service
 
  poll-runner-burger-king:
    image: 'com.scriptterror/poll-runner:0.1'
    env_file:
      - "./poll-runner/config.env"
    ports:
      - 8082:8082
    depends_on:
      - gateway

  telegram-bot:
    hostname: "telegram-bot"
    env_file:
      - "./telegram-bot/config.env"
    container_name: "telegram-bot"
    image: 'com.scriptterror/telegram-bot:0.1'
    ports:
      - 8081:8081
    depends_on:
      - gateway
      - poll-runner-burger-king
