version: '3.7'
services:
  gateway:
    hostname: "gateway"
    container_name: "gateway"
    image: 'com.scriptterror/gateway:0.1'
    env_file:
      - "./gateway/config.env"
    ports:
      - 8080:8080
    networks:
      - front-network
      - back-network

  poll-runner-burger-king:
    hostname: "poll-runner-burger-king"
    container_name: "poll-runner-burger-king"
    image: 'com.scriptterror/poll-runner:0.1'
    env_file:
      - "./poll-runner/config.env"
    ports:
      - 8082:8080
    depends_on:
      - gateway
    networks:
      - back-network

  telegram-bot:
    hostname: "telegram-bot"
    env_file:
      - "./telegram-bot/config.env"
    container_name: "telegram-bot"
    image: 'com.scriptterror/telegram-bot:0.1'
    ports:
      - 8081:8080
    depends_on:
      - gateway
      - poll-runner-burger-king
    networks:
      - front-network

networks:
  front-network: {}
  back-network: {}