version: '3'
services:
  gateway:
    container_name: "gateway"
    image: 'com.scriptterror/gateway:0.1'
    ports:
      - 8080:8080
    tty: true

  poll-runner:
    container_name: "poll-runner"
    image: 'com.scriptterror/poll-runner:0.1'
    ports:
      - 8082:8082
    tty: true
    depends_on:
      - gateway
 

  telegram-bot:
    env_file:
      - "config.env"
    container_name: "telegram-bot"
    image: 'com.scriptterror/telegram-bot:0.1'
    ports:
      - 8081:8081
    tty: true
    depends_on:
      - gateway
      - poll-runner
