zuul:
  routes:
    telegram-bot:
      path: /telegram-bot/**
      url: http://localhost:8081
    poll-runnner-burger-king:
      path: /poll-runner-burger-king/**
      url: http://localhost:8082

