zuul:
  ignoredServices: '*'
  routes:
    telegram-bot:
      path: /telegram-bot/**
      serviceId: telegram-bot
    poll-runnner-burger-king:
      path: /poll-runner-burger-king/**
      serviceid: poll-runner-burger-king
spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

