zuul:
  routes:
    telegram-bot:
      path: /telegram-bot/**
      url: http://telegram-bot:8091
    poll-runnner-burger-king:
      path: /poll-runner-burger-king/**
      url: http://poll-runner-burger-king:8092

logging:
  level:
    root: INFO
