server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: discovery-service
