server:
  port: 8083

eureka:
  instance:
    hostname: discovery-service
    virtual-host-name: discovery-service
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: discovery-service