bot:
  api-key: ENC(zpPeR6ohWWQYA/2XrbhDH248pQKnvgNa/Rp3RdZuvSpd6gXlRarAp2mONSsGR4RPuWcYhKMFv6s=)
  name: ENC(NDr1pxYNLiiIxuEkiDPIRkXFEaXrdU2r)
  proxy:
    host: ENC(p2h/Dvkbd3XYKUaMoABuO6O5KCn7Ja0H)
    port: ENC(sWqST9+U5SuqxICk4aYX5A==)
    user: ENC(0qcmDoJN+xKmP8X8TV22/w==)
    password: ENC(0qcmDoJN+xKmP8X8TV22/w==)



jasypt:
  encryptor:
    bean: encryptorBean
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}